In [4]:
from acrobot_vec import Acrobot
import numpy as np

model = Acrobot()

start_state = np.zeros((4, 4))
dt = 2e-3
control = 5 * np.ones((4, 1))
num_steps = int(1/dt)

print(model.propagate(start_state, control, num_steps, dt), "[-0.50301444,  1.74423944,  0.56988041,  0.87424303]")

[[-0.50301444  1.74423944  0.56988041  0.87424303]
 [-0.50301444  1.74423944  0.56988041  0.87424303]
 [-0.50301444  1.74423944  0.56988041  0.87424303]
 [-0.50301444  1.74423944  0.56988041  0.87424303]] [-0.50301444,  1.74423944,  0.56988041,  0.87424303]


In [2]:
import pickle
 
def load_data(model, env, traj_id):
    filepath = lambda var: "/media/arclabdl1/HD1/Linjun/data/kinodynamic/{model}/{env}/{var}_{id}.pkl".format(model=model,env=env, var=var, id=traj_id)      
    load_pkl = lambda var: pickle.load(open(filepath(var), "rb"))
    keys = ["control", "path", "start_goal", "time", 'cost']
    return dict(zip(keys, [load_pkl(key) for key in keys]))
 
data = load_data('acrobot_obs', 0, 0)
path = data['path']

In [3]:
def get_obs(model, filetype):
    def filepath (model, env_id, filetype):
            return "/media/arclabdl1/HD1/Linjun/data/kinodynamic/{model}/{filetype}_{env_id}.pkl".format(model=model, env_id=env_id, filetype=filetype)
    def loader(model, env_id, filetype): 
        return pickle.load(open(filepath(model, env_id, filetype), "rb"))
    #obs_list = [loader(model, env_id, "obs") for env_id in range(10)]
    obs_list = np.array([loader(model, env_id, "obs").reshape(-1, 2) for env_id in range(10)])
    return obs_list
obs_list = get_obs('acrobot_obs', 0)
# obs_list

In [1]:
env_id = 0
print(model.valid_state(path[0:2], obs_list[env_id]), "should be [True, True]")
print(model.valid_state(path[0:2], np.array([[0, 0], [100, 100]])), "should be [False, False]")

NameError: name 'model' is not defined

In [5]:
model.get_loss(path[:2,:], path[-1], [1, 1, 0.5, 0.5])

[ 0.75361788 -1.72460691]


array([4.55021196, 5.97158282])

In [1]:
import numpy as np
from acrobot_vec_tv import Acrobot
model = Acrobot()

start_state = np.zeros((4, 4))
dt = 2e-3
control = 5 * np.ones((4, 1))
num_steps = np.ones(4)/dt
num_steps[1] *= 2
num_steps[2] *= 3
num_steps[3] *= 4


print(model.propagate(start_state, control, num_steps, dt), "[-0.50301444,  1.74423944,  0.56988041,  0.87424303]")

[[-0.50301444  1.74423944  0.56988041  0.87424303]
 [-0.01393241  2.22872942 -0.70488269  1.20547831]
 [-0.43757336 -2.87112708  0.91750404  0.91190527]
 [-0.74730027  0.92667683 -1.40051652  5.2341118 ]] [-0.50301444,  1.74423944,  0.56988041,  0.87424303]
